version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::781014165239:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-XZJ0EWL9U2IE"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::781014165239:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1VXTSDST0H3UV"
cloudformation_execution_role = "arn:aws:iam::781014165239:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-4G5KFA4CSODC"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-byz1789dhebe"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::781014165239:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-12KESW45T2QV6"
cloudformation_execution_role = "arn:aws:iam::781014165239:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1425D35R79255"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1mcgk1yg737p7"
image_repository = ""
region = "us-east-1"
